### PR TITLE
feat(wallet): build real CLSAG ring transactions in the CLI thin wallet

### LINKED ISSUE #614: wallet: port botho-wallet CLI TransactionBuilder to CLSAG ring format (follow-up to #610)
## Summary
Part 2 of #610, split out per the curator's scoping. The CLI thin wallet (`botho-wallet/src/transaction.rs`) still builds the legacy `botho-tx-v1` flat transaction: plaintext recipient view/spend keys, no ring signature, no key images, no cluster tags. The node's `tx_submit` bincode-deserializes `botho::transaction::Transaction` (CLSAG) and rejects the wallet's txs with `io error: unexpected end of file`.

Until this is ported, **nobody can transact from the CLI wallet** — verified live on the 3.0.0 testnet 2026-07-02. Web wallet (wasm-signer) and mobile (rust-bridge) have their own correct stacks and are unaffected.

## Scope
Port `TransactionBuilder::build_transfer_with_metadata` and its supporting types to the real transaction format:
- Ring member selection via `chain_getOutputs` (the wallet-side decoy selector in `botho-wallet/src/decoy_selection.rs` already exists — wire it in)
- Key image computation, CLSAG signing (reuse `bth-crypto-ring-signature` / the same crates the node uses)
- Cluster-tag blending for change outputs (#249 pending-tags machinery already exists wallet-side)
- bincode serialization matching `botho::transaction::Transaction`
- Reference implementation: node-side `Wallet::create_private_transaction` (botho/src/wallet.rs:426)

## Acceptance criteria
- [ ] `botho-wallet send` produces a tx the node accepts and confirms on testnet
- [ ] Fee handling respects the consensus fee floor (query `estimateFee`; structural MIN_TX_FEE dominates at zero cluster wealth)
- [ ] Integration test: build a tx against fixture UTXOs and bincode-round-trip it through `botho::transaction::Transaction::deserialize`
- [ ] Legacy `botho-tx-v1` code removed or clearly quarantined (per CLAUDE.md code-preservation, prefer stashing/commenting with rationale over silent deletion)

## Dependencies
- #610 (serde wire fix) should land first — connect/sync must work before send can be tested end-to-end.
- Mind #611 (decoy clamp panic) when spending young UTXOs in tests.

Mainnet blocker 4 in PLAN.md (refreshed in PR #612).

### PR DESCRIPTION
**Pull request by rjwalters**
## Summary

The CLI thin wallet (`botho-wallet`) still built the legacy flat `botho-tx-v1`
transaction (plaintext recipient keys, no ring signature, a
cryptographically-broken SHA256 stealth output). The node's `tx_submit`
bincode-deserializes `botho::transaction::Transaction` (CLSAG) and rejected
every CLI tx with `unexpected end of file` — nobody could transact from the CLI
wallet. This ports the builder to the real CLSAG ring format so the node
accepts and confirms wallet-built transactions. Closes #614 (mainnet blocker 4).

## Changes

- **Deps**: add `bth-transaction-clsag` and `bth-transaction-types` to
  `botho-wallet/Cargo.toml`. `transaction.rs` now imports the real
  `Transaction`, `TxOutput`, `ClsagRingInput`, `RingMember`, `MIN_RING_SIZE`,
  `MIN_TX_FEE` — the same crate the node exposes as `botho::transaction`.
- **Legacy quarantine**: the flat `Transaction`/`TxInput`/`TxOutput` (whose
  `TxOutput::new` used `SHA256(view||spend||amount||random)` instead of the
  Ristretto DH stealth protocol, so recipients could never detect the output)
  are preserved in `botho-wallet/src/transaction_legacy.rs` with a rationale
  doc comment — not silently deleted (CLAUDE.md code-preservation).
- **Ring sourcing over RPC** (`ring_builder.rs`): `fetch_decoy_ring_members`
  computes the ±10% age band (`AGE_SIMILARITY_SPREAD_BPS = 1_000`) from the real
  input's age, fetches candidates via `chain_getOutputs`, excludes own inputs,
  parses hex fields into `RingMember` (recomputing the transparent commitment
  identically to the node's `RingMember::from_output`), **shuffles**, and takes
  `MIN_RING_SIZE - 1`. Inputs younger than `MIN_DECOY_AGE_BLOCKS = 10` get a
  clean user-facing error, never a degenerate-band panic (mirrors #611/#618).
- **Builder**: `build_transfer_with_metadata` is now async, fetches an
  age-similar decoy ring per input, and assembles a ring-size-20 CLSAG ring with
  the real input at a randomized position. Outputs inherit merged+decayed
  cluster tags from the inputs (`merge_weighted` @
  `DEFAULT_CLUSTER_DECAY_RATE = 50_000`), matching the node. The #249
  pending-change-tags machinery is preserved (change output's `public_key`).
- **send.rs**: enforces the consensus fee floor via `max(estimate, MIN_TX_FEE)`
  (structural `MIN_TX_FEE = 100_000_000` dominates at zero cluster wealth) and
  serializes via bincode hex through `to_tx_hex`.
- **decoy_selection.rs**: `DecoySelectionConfig` default ring size 11 -> 20;
  age policy switched from the fingerprintable 2× ratio to the node's ±10% band
  (`age_similarity_band`); eligible pool shuffled before take-N; young-input
  guard. Tests updated; integration suite ported to the CLSAG model.

## Acceptance Criteria Verification

| Criterion | Status | Verification |
|-----------|--------|--------------|
| `botho-wallet send` produces a tx the node accepts | ⏳ deferred | Cannot run live send from CI; covered by the round-trip + full build/sign/verify unit tests below. Deferred to operator on the 3.0.0 testnet. |
| Fee handling respects the consensus fee floor | ✅ | `send.rs` uses `.max(MIN_TX_FEE)`; builds reject nothing below it. |
| Integration test: build + bincode-round-trip through node `Transaction` | ✅ | `test_build_signed_transaction_roundtrips_and_verifies` + `test_transaction_serialization_roundtrips_through_node_type` decode as `bth_transaction_clsag::Transaction` and pass `verify_ring_signatures()`; ring size asserted == 20. |
| Legacy code removed or clearly quarantined | ✅ | `transaction_legacy.rs` with doc comment; wired in `lib.rs`/`main.rs`. |
| Ring size = 20 (MIN_RING_SIZE) | ✅ | `fetch_decoy_ring_members` takes `MIN_RING_SIZE-1`; assertions in tests. |
| ±10% age band, not fingerprintable | ✅ | `age_similarity_band` (`AGE_SIMILARITY_SPREAD_BPS`); `test_decoy_selection_enforces_age_similarity`. |
| Shuffled decoys | ✅ | `pool.shuffle` in ring_builder + `select_decoys`; `test_select_decoys_is_randomized`. |
| Young-input clean error (no panic) | ✅ | `test_young_input_rejected_cleanly`, `test_select_decoys_young_input_rejected`. |
| Output detectability (the curator's bug class) | ✅ | `test_output_is_detectable_by_recipient`: recipient's `WalletScanner::check_ownership` detects the produced `TxOutput` (Some(0)); sender does not; sender detects change. |

## Test Plan

- `cargo test -p botho-wallet` — 182 tests pass (112 lib, 56 integration, 2 doc, plus bin).
- `cargo build -p botho-wallet` and `--no-default-features` both clean.
- `cargo fmt -p botho-wallet -- --check` clean; `cargo clippy -p botho-wallet` introduces no new warnings in the touched files.
- **Deferred to operator**: live `botho-wallet send <addr> 0.001` on the 3.0.0 testnet to confirm on-chain acceptance (cannot run from CI).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by rjwalters** [comment]
## Judge Review — Changes Requested

The wallet-crate work here is excellent and the cryptographic port is correct in every dimension I checked (details below). **But the workspace does not compile**, so I can't approve: CI `cargo build --workspace (Linux)` is **red** and `mergeStateStatus` is **UNSTABLE**. This is a mechanical downstream-caller fix, not a rework of the crypto.

### Blocker: `botho-desktop` was not updated for the new `build_transfer` API

This PR changed the public `TransactionBuilder::build_transfer` from a synchronous 3‑arg method to an **async 4‑arg** method (`async fn build_transfer(&self, rpc: &mut RpcPool, recipient, amount, fee)`). The Tauri desktop crate still calls the old signature:

`web/packages/desktop/src-tauri/src/wallet.rs`
- **L529 / L538** — `builder.build_transfer(&recipient, amount, fee).map_err(...)` → `error[E0061]` (4 args, 3 supplied) and `error[E0599]` (`.map_err` on an `impl Future` — missing `.await`). Both `PrivacyLevel::Standard` and `PrivacyLevel::Private` arms.
- **L544** — `tx.to_hex()`: the new `bth_transaction_clsag::Transaction` has **no `to_hex()`** (confirmed — the compiler stopped after 4 errors before reaching this). The new serialization entry point is `transaction::to_tx_hex(&tx)`.

`rpc` is already in scope at L478, so the fix is roughly `builder.build_transfer(&mut rpc, &recipient, amount, fee).await.map_err(...)` for both arms, plus swapping `tx.to_hex()` → `to_tx_hex(&tx)?` and importing it. Please also confirm the borrow of `&mut rpc` for the build call releases before the L543 `rpc.submit_transaction` call (it should, since the builder returns owned data).

**Root cause / process note:** `cargo build -p botho-wallet` and `--no-default-features` both pass in isolation (I reproduced this), which is what the PR tested — but the changed public API has a downstream consumer in the workspace. Please run `cargo build --workspace` (and ideally `cargo test --workspace`) before re-requesting review.

### Everything else verified and passing — no changes needed here

- **Crypto correctness (P1):** Build path mirrors the node reference `create_private_transaction_impl` step-for-step: inherited cluster tags @ `DEFAULT_CLUSTER_DECAY_RATE=50_000`; outputs via the real Ristretto‑DH `TxOutput::new_with_cluster_tags` (not home-rolled hashing); preliminary empty-input tx → `signing_hash()` used as the CLSAG message; per-input `recover_spend_key` → `RingMember::from_output` → real+decoys → `ring.shuffle(OsRng)` → `ClsagRingInput::new`. Real input position is **uniformly random per ring** (OsRng shuffle, not fixed index 0). Change output goes through the same stealth construction.
- **Wire compatibility (P2) — CONFIRMED:** `botho/src/transaction.rs` is `pub use bth_transaction_clsag::*;`, so the node's `crate::transaction::Transaction` that `tx_submit` bincode-decodes (`rpc/mod.rs:1623`) **is literally** `bth_transaction_clsag::Transaction`. The round-trip tests decode into that exact type (not a twin) and pass `verify_ring_signatures()`. The round-trip proves real wire compatibility.
- **Privacy invariants (P3):** Ring size exactly `MIN_RING_SIZE=20` (asserted in tests). Wallet `age_similarity_band` is **byte-identical** to the node's (`AGE_SIMILARITY_SPREAD_BPS=1_000`, `saturating_sub(delta).max(MIN_DECOY_AGE_BLOCKS)`, same rounding, same 10-block floor). Eligible pool shuffled with `OsRng` before take‑N (production path, not seeded). Own inputs excluded via `exclude_keys`.
- **Behavioral safety (P4):** Young-input (<10 blocks) guard fires in `fetch_decoy_ring_members` before any RPC call → clean actionable Err ("too new… wait for at least 10 confirmations"), no panic. Insufficient decoys → typed error, no panic. `send.rs` enforces `fee_estimate.total_fee.max(MIN_TX_FEE)`.
- **Quarantine discipline (P5):** `transaction_legacy.rs` carries a thorough rationale doc comment, `#![allow(dead_code)]`, and **zero production imports** (verified). Clearly marked non-functional/deprecated.
- **Test quality (P6):** `test_output_is_detectable_by_recipient` uses a real `WalletScanner` against a **distinct** recipient keypair, asserts recipient detects `Some(0)`, sender does **not** detect the recipient output, and sender **does** detect change. Verify tests call the crate's actual `verify_ring_signatures()`. No mocked crypto.
- **Integration seams (P7):** `send.rs` async rewiring is correct; `sync_wallet` UTXOs feed the builder with correct amounts/tags/derivation params; #249 pending-change-tags still written via `change_output_public_key`.

### On the flagged "never-relax band" deviation — approved on the merits
The wallet returns a clean typed error rather than falling back to a wider/nearest-age band when the ±10% window is under-populated, whereas the node's ledger selector can relax. Ruling: **acceptable, keep it.** The two selections are independent (no cross-compatibility concern), and refusing to send is strictly safer for privacy than silently widening the age band and fingerprinting CLI-wallet txs — exactly the failure this issue set out to fix. On a sparse chain a user gets an actionable "not enough age-similar outputs" message rather than a degraded-anonymity transaction. If sparse-chain UX becomes a real problem pre-mainnet, revisit as a follow-up, but do not trade privacy for it here.

**Local results:** `cargo test -p botho-wallet` 112 lib + 56 integration + 2 doc all pass; `cargo build -p botho-wallet --no-default-features` clean; `cargo fmt -p botho-wallet -- --check` clean. The only failure is the workspace build via `botho-desktop`.

Fix the desktop caller so `cargo build --workspace` is green (and merge state returns to CLEAN) and re-request review — the rest is ready.

**Comment by rjwalters** [comment]
## Doctor — Feedback Addressed

Fixed the sole blocker (downstream `botho-desktop` caller not updated for the new async `build_transfer` API). Commit `cf0640d`.

`web/packages/desktop/src-tauri/src/wallet.rs`:
- Both `PrivacyLevel::Standard` and `PrivacyLevel::Private` arms now call `builder.build_transfer(&mut rpc, &recipient, amount, fee).await` (in-scope `rpc` from L478; the `&mut rpc` borrow releases before the later `rpc.submit_transaction`, since the builder returns an owned `Transaction`).
- Swapped the removed `tx.to_hex()` for `to_tx_hex(&tx)` (imported from `botho_wallet::transaction`), matching `send.rs`.

Verified with a full workspace build this time:
- `cargo build --workspace` — green (Finished, warnings only)
- `cargo test -p botho-wallet` — 112 lib + 56 integration + 2 doc, all pass
- `cargo fmt --all -- --check` — clean

No crypto/privacy changes; this is the mechanical caller fix requested. Re-requesting review.

**Comment by rjwalters** [comment]
## Judge Review — Approved

Follow-up pass scoped to the delta from my previously-reviewed commit (`fb40b24`) to HEAD (`cf0640d`). Approving.

### Delta verification
`git diff fb40b24 cf0640d` touches exactly one file — `web/packages/desktop/src-tauri/src/wallet.rs`, +9/-4 — and nothing else. The crypto/privacy/wire-compat paths I approved last pass are untouched. This is precisely the requested mechanical caller fix:
- Import `to_tx_hex` added to the `botho_wallet::transaction` use block.
- Both `PrivacyLevel::Standard` and `PrivacyLevel::Private` arms now call `builder.build_transfer(&mut rpc, &recipient, amount, fee).await` (async 4-arg).
- `tx.to_hex()` swapped for `to_tx_hex(&tx).map_err(...)?`, matching `send.rs`.

### Borrow / error-handling sanity check
- `rpc` is `let mut rpc = RpcPool::new(discovery)` at L478, so `&mut rpc` is available. The `&mut rpc` borrow taken by `build_transfer(...).await` is released at the end of the statement (the builder returns an owned `Transaction`), so the later `rpc.submit_transaction(...)` at L548 reborrows cleanly — no conflict. Confirmed by a green compile, not just inspection.
- Error strings preserve the surrounding style: `Failed to build transaction: {e}`, new `Failed to serialize transaction: {e}` for the fallible `to_tx_hex`, and `Failed to submit transaction: {e}`. All user-facing and reasonable.

### CI + local verification
- `gh pr checks 620`: all 4 green — build --workspace (Linux), rustfmt, typecheck+vitest+worker, coverage.
- `mergeStateStatus`: CLEAN; `mergeable`: MERGEABLE.
- Local `cargo build --workspace`: Finished (warnings only).
- Local `cargo test -p botho-wallet`: 112 lib + 56 integration + 2 doc, all pass.

The blocker from my prior pass is resolved and the previously-approved substance is unchanged. Ready to merge.
